
//////////////////////////////////////////////////////////////////////
// Automatically generated by Bradley's GumpStudio and roadmaster's 
// exporter.dll,  Special thanks goes to Daegon whose work the exporter
// was based off of, and Shadow wolf for his Template Idea.
//////////////////////////////////////////////////////////////////////
//#define RunUo2_0

using System;
using Server;
using Server.Gumps;
using Server.Network;
using Server.Commands;

namespace Server.Gumps
{
    public class MenuChoiceTailor : Gump
    {
        public static void Initialize()
        {
            CommandSystem.Register("MenuChoiceTailor", AccessLevel.Administrator, new CommandEventHandler(MenuChoiceTailor_OnCommand));
        }

        [Usage("MenuChoiceTailor")]
        [Description("Makes a call to your custom gump.")]
        public static void MenuChoiceTailor_OnCommand(CommandEventArgs e)
        {
            e.Mobile.SendGump( new MenuChoiceTailor() );
        }

        public MenuChoiceTailor() : base( 0, 0 )
        {
            this.Closable=true;
			this.Disposable=true;
			this.Draggable=true;
			this.Resizable=false;

			AddPage(0);
			AddBackground(284, 203, 241, 149, 2620);
			AddAlphaRegion(290, 212, 229, 131);
			AddLabel(343, 316, 1150, @"Classic");
			AddLabel(457, 316, 1150, @"Modern");
			AddButton(312, 306, 2151, 2154, 1, GumpButtonType.Reply, 0);
			AddButton(427, 306, 2151, 2154, 2, GumpButtonType.Reply, 0);
			AddLabel(318, 221, 1150, @"Please choose a menu style:");
			AddItem(490, 322, 3995);
			AddImage(373, 249, 5579);
			AddItem(271, 194, 5991);
			AddItem(273, 186, 3580);
			AddItem(258, 203, 3997);
			

            
        }

        

        public override void OnResponse(NetState sender, RelayInfo info)
        {
            Mobile from = sender.Mobile;

            switch(info.ButtonID)
            {
                				case 0:
				{

					break;
				}
				case 1:
				{

					break;
				}
				case 2:
				{

					break;
				}

            }
        }
    }
}